import Head from "next/head";
import Layout from "@/components/Layout";
import Hero from "@/components/Hero";
import Quote from "@/components/Quote";
import PartnersLogos from "@/components/PartnersLogos";
import HowWorks from "@/components/HowWorks";
import Context from "@/components/Context";
import Benefits from "@/components/Benefits";
import Industries from "@/components/Industries";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Hero></Hero>
        <PartnersLogos></PartnersLogos>
        <Quote></Quote>
        <Context></Context>
        <Industries></Industries>
        <HowWorks></HowWorks>
        <Benefits></Benefits>
      </Layout>
    </>
  );
}
